var vcbl={
"RUS":{
    "lang": "Язык",
    "treePanelTitle": "Меню",
    "titleStartPage": "Стартовая страница",
    "titleNewPage": "Новая страница",
    "filterPanelTitle": "Фильтры",
    "emptyTextFilter": "Чтобы добавить фильтр, перетащите заголовок столбца в эту область.",
    "applyBut": "Применить",
    "saveBut": "Сохранить",
    "cancelBut": "Отмена",
    "saveAsBut": "Сохранить как",
    "settingBut": "Настройка",
    "exitBut": "Выход",
    "closeBut": "Закрыть",
    "createTemplate": "Создание шаблона",
    "nameLong": "Наименование",
    "titleSettingsTableWin": "Настройка таблицы",
    "titleSettingsChartWin": "Настройка графика",
    "labelDS": "Источник данных",
    "labelAggregate": "Агрегировать",
    "nameField": "Имя поля",
    "funcAgr": "Функция агрегирования",
    "dinamicFilter": "Фильтр отчета",
    "staticFilter": "Фильтр таблицы",
    "viewMode": "Отображение",
    "labelChooseChart": "Выберите график",
    "showMultiPanelMenu": "Панель инструментов",
    "hideMultiPanelMenu": "Панель инструментов",
    "filtersTitle": "Фильтры",
    "chooseParentFilterWin": "Категории",
    "chooseChildFilterWin": "Доп. условие",
    "chooseItemFilterWin": "Выберите элементы",
    "availableFilterWin": "Доступно",
    "selectedFilterWin": "Выбрано",
    "conditionLabel": "Условие",
    "dateLabel": "Дата",
    "dateToLabel": "по",
    "digitLabel": "Число",
    "strLabel": "Текст",
    "limitDsLabel": "Ограничить",
    "statusTitle": "Статус",
    "needSelReport": "Необходимо выбрать отчет",
    "cantDelete": "Удаление невозможно",
    "delReportTitle": "Удаление отчета",
    "wantToDelReport": "Вы действительно хотите удалить этот отчёт?",
    "reportSaved": "Отчёт сохранён",
    "deleteReportBut": "Удалить отчёт",
    "addFolderBut": "Добавить папку",
    "addingFolders": "Добавление папки",
    "tooltipChangeSettings": "Настройки",
    "tooltipSplitVerticallyL": "Добавить слева",
    "tooltipSplitVerticallyR": "Добавить справа",
    "tooltipSplitHorizontallyT": "Добавить сверху ",
    "tooltipSplitHorizontallyB": "Добавить  снизу",
    "tooltipDownloadXLS": "Скачать XLS",
    "tooltipDownloadSVG": "Скачать SVG",
    "tooltipDownloadPNG": "Скачать PNG",
    "tooltipClose": "Закрыть",
    "listReports": "Список отчётов",
    "createNewReport": "Новый отчёт",
    "userPrevFilters": "Использовать предыдущие фильтры",
    "selectAll": "Выделить всё",
    "inNewWin": "Открыть в новом окне",
    "inCurWin": "Открыть",
    "unsavedReportMes": "Отчёт был изменен. Сохранить изменения?",
    "openBut": "Открыть",
    "curReportIsEmpty": "Отчёт пуст.",
    "clickText": "Нажмите",
    "hereText": "здесь",
    "newTableText": "для создания новой таблицы.",
    "newChartText": "для создания нового графика.",
    "fullInfo": "Полная информация",
    "sprText": "Справочник",
    "inText": "Список",
    "betweenText": "Диапазон",
    "likeText": "Содержит",
    "basicReportsText": "Базовые отчёты",
    "errorTakeFields": "Ошибка получения полей!",
    "errorTakeObject": "Ошибка получения объекта!",
    "errorLoadUserID": "Ошибка загрузки номера пользователя!",
    "errorLoadDS": "Ошибка загрузки наборов данных!",
    "errorLoadBasicReport": "Ошибка загрузки базовых отчётов!",
    "errorTakeReportID": "Ошибка получения номера отчёта!",
    "errorDeleteReportID": "Ошибка удаления отчёта!",
    "errorSendToItemID": "Ошибка запроса номера элемента!",
    "errorChangeToItemID": "Ошибка изменения элемента!",
    "errorDeleteItemID": "Ошибка удаления элемента!",
    "errorSaveMultiPanel": "Ошибка сохранения отчёта!",
    "errorSaveNewReportName": "Ошибка сохранения наименования нового отчёта!",
    "errorLoadReportPanel": "Ошибка загрузки элемента!",
    "errorLoadTableData": "Ошибка загрузки табличных данных!",
    "errorLoadColumns": "Ошибка загрузки столбцов!",
    "errorLoadCount": "Ошибка загрузки количества записей!",
    "errorLoadFullInfoCell": "Ошибка загрузки полной информации ячейки!",
    "errorLoadTableSettings": "Ошибка загрузки настроек таблицы!",
    "errorSelectTypeChart": "Ошибка выбора типа графика!",
    "errorSelectTypeFilter": "Ошибка выбора типа фильтра!",
    "errorAddFolder": "Ошибка добавления папки!",
    "errorLoadListReports": "Ошибка загрузки списка отчётов!",
    "errorLoadFiltersCombo_2": "Ошибка загрузки фильтов!",
    "errorLoadSubfilter": "Ошибка загрузки подфильтров!",
    "errorSendToFilterID": "Ошибка запроса номера фильтра!",
    "errorChangeToFilterID": "Ошибка изменения фильтра!",
    "errorDeleteFilter": "Ошибка удаления фильтра!",
    "errorLoadAllFilters": "Ошибка загрузки всех фильтров!",
    "errorLoadChartData": "Ошибка загрузки данных для графика!",
    "errorMemoShortFilter": "Фильтрация по этому полю невозможна!",
    "errorJDBCConnection": "Отсутствует подключение к базе данных!",
    "errorAccessDenied": "ACCESS DENIED",
    "sendFeedback": "Отправьте нам свой отзыв",
    "inDevelopment": "Это приложение все еще находится в разработке. ",
    "seeWhatsChanging": "Посмотрите, что меняется.",
    "myReportsText": "Мои отчеты",
    "reportsText": "Отчеты",
    "reportsText_2": "Базовые отчеты",
    "fromStartYear": "С начала года",
    "fromStartHalfYear": "С начала полугодия",
    "fromStartQuarter": "С начала квартала",
    "fromStartMonth": "С начала месяца",
    "sortWinTitle": "Настройка сортировки",
    "addSortLevelBut": "Добавить уровень",
    "delSortLevelBut": "Удалить уровень",
    "nameSortColumn": "Наименование",
    "nameDirColumn": "Направление",
    "viewModeEditorVert": "По вертикали",
    "viewModeEditorHor": "По горизонтали",
    "viewModeEditorFact": "Значение",
    "regexpYear": "Должно быть указано число: например 2012",
    "regexpYearList": "Должен быть указан список чисел: например 2012,2013,2014",
    "regexpQuarter": "Должно быть указано число: например 3",
    "regexpQuarterList": "Должен быть указан список чисел: например 1,2,4",
    "regexpMonth": "Должно быть указано число: например 9",
    "regexpMonthList": "Должен быть указан список чисел: например 1,10,11",
    "regexpDigit": "Должно быть указано число: например 962.12",
    "regexpDigitList": "Должен быть указан список чисел: например 895.3,1234,85.999",
    "chartToGrid": "Построить график",
    "step1TitleText": "Тип графика",
    "step2TitleText": "Настройка оси X",
    "step2TitleTextSankey": "Настройка узлов",
    "axisXName": "Название оси",
    "step3TitleText": "Настройка оси Y",
    "step3TitleTextSankey": "Значение",
    "step3TitleTextPie": "Значения",
    "axisYName": "Название оси",
    "step4TitleText": "Настройка серии",
    "step4TitleTextPie": "Серии",
    "step5TitleText": "Дополнительные параметры",
    "stepText": "Шаг",
    "fromText": "из",
    "forwardText": "Далее",
    "backText": "Назад",
    "displayText": "Отобразить",
    "colorText": "Цвет",
    "saveColorText": "Сохранить цвет",
    "otherText": "Прочее",
    "enableAddSetText": "Включить доп настройки",
    "groupedInOtherText": "Группировать в \"прочее\" ",
    "allButFirstText": "всё, кроме первых",
    "partsText": "-х частей.",
    "pickOutText": "Выделить",
    "chooseAllText": "Выбрать всё",
    "byDefaultText": "По умолчанию",
    "showLabelsTitle": "Показать подписи",
    "showLegendTitle": "Показать легенду",
    "leftTitle": "Слева",
    "rightTitle": "Справа",
    "topTitle": "Сверху",
    "bottomTitle": "Снизу",
    "fontSizeTitle": "Размер шрифта",
    "copyToClipboard": "Копировать в буфер обмена",
    "pasteFromClipboard": "Вставить из буфера обмена",
    "elementForClipboard": "Элемент: ",
    "fromForClipboard": " из ",
    "copyTextForClipboard": " скопирован в буфер обмена.",
    "clipboardTitle": "Буфер обмена",
    "clearClipboard": "Очистить буфер обмена",
    "nameGridClipboard": "Наименование элемента",
    "nameReportGridClipboard": "Наименование отчета",
    "typeGridClipboard": "Тип",
    "remElGridClipboard": "Удалить",
    "pasteElGridClipboard": "Вставить",
    "errorMaxDeepPivot": "Максимальная вложенность должна бать не более",
    "errorNeedVertField": "Необходимо поле с вертикальным отображением.",
    "errorNeedHorField": "Необходимо поле с горизонтальным отображением.",
    "errorMoreOneFactFiled": "Поле со значением может быть только одно.",
    "errorNeedSelectFiled": "Необходимо выбрать поле.",
    "errorSepMinWidthPanel": "Добавление невозможно, увеличьте ширину панели.",
    "errorSepMinHeightPanel": "Добавление невозможно, увеличьте высоту панели.",
    "maxSankeyItemsCount": "Максимальное количество элементов",
    "sankeyPaddingBetweenElements": "Отступы между элементами",
    "globalSettings": "Глобальные настройки",
    "toolbarDockSet": "Расположение меню",
    "toolbarDockSetTop": "Вверху",
    "toolbarDockSetBottom": "Внизу",
    "toolbarDockSetLeft": "Слева",
    "toolbarDockSetRight": "Справа",
    "sankeyColoring": "Раскраска",
    "sankeyColoringOnLeft": "Слева",
    "sankeyColoringOnRight": "Справа",
    "sankeyUnit": "Размерность чисел",
    "sourceTextForChart": "Источник: Refinitiv",
    "showLineColor": "Окрашивать линии",
    "helpFAQText": "Помощь",
    "warningExcelPart1": "Будет выгружено не более",
    "warningExcelPart2": "первых строк из",
    "warningExcelPart3": ".",
    "warningText": "Предупреждение",
    "tooltipAlert": "Необработанное событие",
    "warningFuncAgr": "Для использования функции агрегирования необходимо скрыть поле ",
    "warningFuncAgr2": "Для отображения данного поля необходимо убрать функцию агрегирования с поля ",
    "warningTreeMapUse": "Для работы с данным типом графика необходимо отфильтровать таблицу по полю(полям): ",
    "warningXRangeUse": "Данный тип графика хорошо применим для датасета \"Ремонты\".",
    "errorLoadMaxCount": "Ошибка загрузки максимального количества скачиваемых записей.",
    "xrangeStartDate": "Дата начала: ",
    "xrangeFinishDate": "Дата окончания: "
},
"ENG":{
    "lang": "Language",
    "treePanelTitle": "Menu",
    "titleStartPage": "Start page",
    "titleNewPage": "Home",
    "filterPanelTitle": "Filters",
    "emptyTextFilter": "To add a filter, drag the column heading to this area.",
    "applyBut": "Apply",
    "saveBut": "Save",
    "cancelBut": "Сancel",
    "saveAsBut": "Save as",
    "settingBut": "Settings",
    "exitBut": "Exit",
    "closeBut": "Close",
    "createTemplate": "Create template",
    "nameLong": "Name",
    "titleSettingsTableWin": "Table settings",
    "titleSettingsChartWin": "Chart settings",
    "labelDS": "Data set",
    "labelAggregate": "Aggregate",
    "nameField": "Field name",
    "funcAgr": "Aggregation function",
    "dinamicFilter": "Report filter",
    "staticFilter": "Data set filter",
    "viewMode": "Display",
    "labelChooseChart": "Select a chart",
    "showMultiPanelMenu": "Title bar and menu",
    "hideMultiPanelMenu": "Title bar and menu",
    "filtersTitle": "Filters",
    "chooseParentFilterWin": "Categories",
    "chooseChildFilterWin": "Additional condition",
    "chooseItemFilterWin": "Choose elements",
    "availableFilterWin": "Available",
    "selectedFilterWin": "Selected",
    "conditionLabel": "Condition",
    "dateLabel": "Date",
    "dateToLabel": "to",
    "digitLabel": "Digit",
    "strLabel": "Text",
    "limitDsLabel": "Limit",
    "statusTitle": "Status",
    "needSelReport": "Select the Report",
    "cantDelete": "Deletion not possible",
    "delReportTitle": "Delete this report",
    "wantToDelReport": "Do you want to delete this report?",
    "reportSaved": "Report is saved",
    "deleteReportBut": "Delete report",
    "addFolderBut": "Add folder",
    "addingFolders": "Adding folders",
    "tooltipChangeSettings": "Settings",
    "tooltipSplitVerticallyL": "Insert left",
    "tooltipSplitVerticallyR": "Insert right",
    "tooltipSplitHorizontallyT": "Insert above",
    "tooltipSplitHorizontallyB": "Insert below",
    "tooltipDownloadXLS": "Download XLS",
    "tooltipDownloadSVG": "Download SVG",
    "tooltipDownloadPNG": "Download PNG",
    "tooltipClose": "Close",
    "listReports": "List of reports",
    "createNewReport": "New report",
    "userPrevFilters": "Use the previous filters ",
    "selectAll": "Select all",
    "inNewWin": "Open in new window",
    "inCurWin": "Open",
    "unsavedReportMes": "The report has been changed. Do you want to save changes?",
    "openBut": "Open",
    "curReportIsEmpty": "The current report is empty.",
    "clickText": "Click",
    "hereText": "here",
    "newTableText": "to create a new table.",
    "newChartText": "to create a new chart.",
    "fullInfo": "Full information",
    "sprText": "Dictionary",
    "inText": "List",
    "betweenText": "Range",
    "likeText": "Contains",
    "basicReportsText": "Basic reports",
    "errorTakeFields": "Error take fields!",
    "errorTakeObject": "Error take object!",
    "errorLoadUserID": "Error load userID!",
    "errorLoadDS": "Error load DS!",
    "errorLoadBasicReport": "Error load basic report!",
    "errorTakeReportID": "Error take reportID!",
    "errorDeleteReportID": "Error delete reportID!",
    "errorSendToItemID": "Error send to itemID!",
    "errorChangeToItemID": "Error change to itemID!",
    "errorDeleteItemID": "Error delete itemID!",
    "errorSaveMultiPanel": "Error save multiPanel!",
    "errorSaveNewReportName": "Error save new report name!",
    "errorLoadReportPanel": "Error load multiPanel!",
    "errorLoadTableData": "Error load table data!",
    "errorLoadColumns": "Error load columns!",
    "errorLoadCount": "Error load count!",
    "errorLoadFullInfoCell": "Error load full info cell!",
    "errorLoadTableSettings": "Error load table settings!",
    "errorSelectTypeChart": "Error select type chart!",
    "errorSelectTypeFilter": "Error select type filter!",
    "errorAddFolder": "Error add folder!",
    "errorLoadListReports": "Error load list reports!",
    "errorLoadFiltersCombo_2": "Error load filters combo_2!",
    "errorLoadSubfilter": "Error load subfilter!",
    "errorSendToFilterID": "Error send to filterID!",
    "errorChangeToFilterID": "Error change to filterID!",
    "errorDeleteFilter": "Error delete filter!",
    "errorLoadAllFilters": "Error load all filters!",
    "errorLoadChartData": "Error loading data for the chart!",
    "errorMemoShortFilter": "Filtering in this field can not be!",
    "errorJDBCConnection": "No connection to the database!",
    "errorAccessDenied": "ACCESS DENIED",
    "sendFeedback": "Send us feedback",
    "inDevelopment": "This application is still in development. ",
    "seeWhatsChanging": "See what\'s changing.",
    "myReportsText": "My Reports",
    "reportsText": "Reports",
    "reportsText_2": "Prebuilt Reports",
    "fromStartYear": "All data since the beginning of the year",
    "fromStartHalfYear": "All data since the beginning of the half-year",
    "fromStartQuarter": "All data since the beginning of the quarter",
    "fromStartMonth": "All data since the beginning of the month",
    "sortWinTitle": "Setting sorting",
    "addSortLevelBut": "Add level",
    "delSortLevelBut": "Delete level",
    "nameSortColumn": "Name",
    "nameDirColumn": "Direction",
    "viewModeEditorVert": "Vertical",
    "viewModeEditorHor": "Horizontal",
    "viewModeEditorFact": "Value",
    "regexpYear": "It must indicate the number, eg 2012",
    "regexpYearList": "Must be specified list of numbers: eg 2012,2013,2014",
    "regexpQuarter": "It must indicate the number, eg 3",
    "regexpQuarterList": "Must be specified list of numbers: eg 1,2,4",
    "regexpMonth": "It must indicate the number, eg 9",
    "regexpMonthList": "Must be specified list of numbers: eg 1,10,11",
    "regexpDigit": "It must indicate the number, eg 962.12",
    "regexpDigitList": "Must be specified list of numbers: eg 895.3,1234,85.999",
    "chartToGrid": "Plot",
    "step1TitleText": "Chart type",
    "step2TitleText": "Setting X-axis",
    "step2TitleTextSankey": "Setting units",
    "axisXName": "Axis name",
    "step3TitleText": "Setting Y-axis",
    "step3TitleTextSankey": "Value",
    "step3TitleTextPie": "Values",
    "axisYName": "Axis name",
    "step4TitleText": "Setting up a series of",
    "step4TitleTextPie": "Series",
    "step5TitleText": "Additional settings",
    "stepText": "Step",
    "fromText": "from",
    "forwardText": "Next",
    "backText": "Back",
    "displayText": "Display",
    "colorText": "Color",
    "saveColorText": "Save color",
    "otherText": "Other",
    "enableAddSetText": "Enable extra settings",
    "groupedInOtherText": "Grouped in the \"other\" ",
    "allButFirstText": "all but the first",
    "partsText": "parts.",
    "pickOutText": "Pick out",
    "chooseAllText": "Choose all",
    "byDefaultText": "By default",
    "showLabelsTitle": "Show captions",
    "showLegendTitle": "Show legend",
    "leftTitle": "Left",
    "rightTitle": "Right",
    "topTitle": "Top",
    "bottomTitle": "Bottom",
    "fontSizeTitle": "Font size",
    "copyToClipboard": "Copy to clipboard",
    "pasteFromClipboard": "Paste from clipboard",
    "elementForClipboard": "Element: ",
    "fromForClipboard": " from ",
    "copyTextForClipboard": " copied to the clipboard.",
    "clipboardTitle": "Clipboard",
    "clearClipboard": "Clear the clipboard",
    "nameGridClipboard": "Element name",
    "nameReportGridClipboard": "Report name",
    "typeGridClipboard": "Type",
    "remElGridClipboard": "Delete",
    "pasteElGridClipboard": "Paste",
    "errorMaxDeepPivot": "Maximum nesting should be no more than",
    "errorNeedVertField": "A field with a vertical display is required",
    "errorNeedHorField": "A field with a horizontal display is required.",
    "errorMoreOneFactFiled": "A field with a value can be only one.",
    "errorNeedSelectFiled": "You must select a field.",
    "errorSepMinWidthPanel": "Adding not possible, increase the width of the panel.",
    "errorSepMinHeightPanel": "Adding not possible, increase the height of the panel.",
    "maxSankeyItemsCount": "Maximum number of items",
    "sankeyPaddingBetweenElements": "Padding between elements",
    "globalSettings": "Global settings",
    "toolbarDockSet": "Location toolbar",
    "toolbarDockSetTop": "Top",
    "toolbarDockSetBottom": "Bottom",
    "toolbarDockSetLeft": "Left",
    "toolbarDockSetRight": "Right",
    "sankeyColoring": "Coloring",
    "sankeyColoringOnLeft": "Left",
    "sankeyColoringOnRight": "On right",
    "sankeyUnit": "The dimension of the numbers",
    "sourceTextForChart": "Source: Refinitiv",
    "showLineColor": "Coloring line",
    "helpFAQText": "Help",
    "warningExcelPart1": "No more than",
    "warningExcelPart2": "first rows of",
    "warningExcelPart3": " will be uploaded.",
    "warningText": "Warning",
    "tooltipAlert": "Unhandled event",
    "warningFuncAgr": "To use the aggregate function, you must hide the field ",
    "warningFuncAgr2": "To display this field, you must remove the aggregate function from the field ",
    "warningTreeMapUse": "To use this type of chart please filter the table by the field (s): ",
    "warningXRangeUse": "This type of chart is well applicable for dataset \"Repairs\".",
    "errorLoadMaxCount": "Error loading the maximum number of downloaded records.",
    "xrangeStartDate": "Date start: ",
    "xrangeFinishDate": "Date finish: "
}
};